INSERT INTO ROLES (name, description) VALUES ('USER','Basic role for any user');
INSERT INTO ROLES (name, description) VALUES ('ADMIN', 'Sysadmin role');
INSERT INTO USERS (username, email, password) VALUES ('tony', 'tony@mail.com', '$2a$10$DXLNjmOBkyk5I315fxF6PuNHzqVmu9wu1L7FmDKd5GIIRzEKpV2RW');
INSERT INTO USERS (username, email, password) VALUES ('mailen', 'mailen@mail.com', '$2a$10$wgGrqFroS.aah424sXywQurq1PY6ns3RhadyxQsbbJVmLgPo3r9fa');
INSERT INTO USERS (username, email, password) VALUES ('migue', 'migue@mail.com','$2a$10$LiLsA082Y8AFvYn2im2QQOblCrozDyz1JwTAV.oMwipbuc97ydUde');
INSERT INTO USERS (username, email, password) VALUES ('tonito', 'tonito@mail.com','$2a$10$3uqmiHB6nmhaF1oM85SAIeJbaG6fr5mps1YO7sFNOod7mM.k0yUzy');
INSERT INTO USER_ROLES (user_id, role_id) VALUES (1,2);
INSERT INTO USER_ROLES (user_id, role_id) VALUES (2,1);
INSERT INTO USER_ROLES (user_id, role_id) VALUES (1,1);
INSERT INTO USER_ROLES (user_id, role_id) VALUES (3,1);
INSERT INTO USER_ROLES (user_id, role_id) VALUES (4,1);
INSERT INTO CATEGORIES (name, description) VALUES ('Category 1', 'This is the description for Category 1');
INSERT INTO CATEGORIES (name, description) VALUES ('Category 2', 'This is the description for Category 2');
INSERT INTO CATEGORIES (name, description) VALUES ('Category 3', 'This is the description for Category 3');
INSERT INTO CATEGORIES (name, description) VALUES ('Category 4', 'This is the description for Category 4');
INSERT INTO VENDORS (name, personal_address, surname, second_surname, user_id) VALUES ('Vendor1', 'Address1','Surname1','SecondSurname1',1);
INSERT INTO VENDORS (name, personal_address, surname, second_surname, user_id) VALUES ('Vendor2', 'Address2','Surname2','SecondSurname2',2);
INSERT INTO CLIENTS (name, surname, second_surname, personal_address, user_id) VALUES ('Client1','Surname1','Second Surname 1','Personal Address 1', 3);
INSERT INTO CLIENTS (name, surname, second_surname, personal_address, user_id) VALUES ('Client 2','Surname 2','Second Surname 2','Personal Address 2', 4);
INSERT INTO PRODUCTS (price, name, description, vendor_id) VALUES (45.2, 'Product 1', 'This is the description of the Product',1);
INSERT INTO PRODUCTS (price, name, description, vendor_id) VALUES (5.6, 'Product 2', 'This is the description of the Product',1);
INSERT INTO PRODUCTS (price, name, description, vendor_id) VALUES (22.6, 'Product 3', 'This is the description of the Product',1);
INSERT INTO PRODUCTS (price, name, description, vendor_id) VALUES (10.5, 'Product 4', 'This is the description of the Product',2);
INSERT INTO PRODUCTS (price, name, description, vendor_id) VALUES (3, 'Product 5', 'This is the description of the Product',2);
INSERT INTO PRODUCTS (price, name, description, vendor_id) VALUES (78.4, 'Product 6', 'This is the description of the Product',2);
INSERT INTO PRODUCTS (price, name, description, vendor_id) VALUES (9.6, 'Product 7', 'This is the description of the Product',2);
INSERT INTO PRODUCTS (price, name, description, vendor_id) VALUES (8.4, 'Product 8', 'This is the description of the Product',2);
INSERT INTO PRODUCTS (price, name, description, vendor_id) VALUES (5.6, 'Product 9', 'This is the description of the Product',2);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (1,1);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (2,1);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (3,2);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (4,3);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (5,4);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (6,1);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (7,1);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (8,2);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (9,3);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (2,3);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (6,2);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (8,1);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (7,4);
INSERT INTO PRODUCTS_CATEGORIES (products_id, categories_id) VALUES (1,4);
INSERT INTO DISCOUNTS (name, percent, description) VALUES ('Discount1',5,'Description 1');
INSERT INTO DISCOUNTS (name, percent, description) VALUES ('Discount2',4.2,'Description 2');
INSERT INTO DISCOUNTS (name, percent, description) VALUES ('Discount3',1.6,'Description 3');
INSERT INTO DISCOUNTS (name, percent, description) VALUES ('Discount4',10,'Description 4');
INSERT INTO DISCOUNTS (name, percent, description) VALUES ('Discount5',6.3,'Description 5');
INSERT INTO TAXES (name, percent, description) VALUES ('Tax1',5,'Description 1');
INSERT INTO TAXES (name, percent, description) VALUES ('Tax2',4.2,'Description 2');
INSERT INTO TAXES (name, percent, description) VALUES ('Tax3',1.6,'Description 3');
INSERT INTO TAXES (name, percent, description) VALUES ('Tax4',10,'Description 4');
INSERT INTO TAXES (name, percent, description) VALUES ('Tax5',6.3,'Description 5');
INSERT INTO INVOICES (date_time) VALUES ('2023-05-17 12:06:56');
INSERT INTO INVOICES (date_time) VALUES ('2023-05-15 01:25:32');
INSERT INTO INVOICES (date_time) VALUES ('2023-04-12 07:35:00');
INSERT INTO INVOICES (date_time) VALUES ('2023-02-24 00:16:39');
INSERT INTO INVOICES (date_time) VALUES ('2023-05-30 08:35:59');
INSERT INTO INVOICES (date_time) VALUES ('2023-01-29 04:00:00');
INSERT INTO INVOICES (date_time) VALUES ('2023-05-01 00:36:00');
INSERT INTO INVOICES (date_time) VALUES ('2023-05-12 00:00:45');
INSERT INTO INVOICES (date_time) VALUES ('2023-05-14 09:00:00');
INSERT INTO INVOICES (date_time) VALUES ('2023-05-10 01:07:00');
INSERT INTO INVOICES (date_time) VALUES ('2023-05-17 00:00:23');
INSERT INTO INVOICES (date_time) VALUES ('2023-05-17 05:00:00');
INSERT INTO INVOICES (date_time) VALUES ('2023-05-17 00:06:00');
INSERT INTO INVOICES_DISCOUNTS (invoice_id, discounts_id) VALUES (1,1);
INSERT INTO INVOICES_DISCOUNTS (invoice_id, discounts_id) VALUES (1,5);
INSERT INTO INVOICES_DISCOUNTS (invoice_id, discounts_id) VALUES (2,3);
INSERT INTO INVOICES_DISCOUNTS (invoice_id, discounts_id) VALUES (3,1);
INSERT INTO INVOICES_DISCOUNTS (invoice_id, discounts_id) VALUES (5,4);
INSERT INTO INVOICES_DISCOUNTS (invoice_id, discounts_id) VALUES (6,5);
INSERT INTO INVOICES_DISCOUNTS (invoice_id, discounts_id) VALUES (1,2);
INSERT INTO INVOICES_DISCOUNTS (invoice_id, discounts_id) VALUES (1,3);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (1,1);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (1,2);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (1,3);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (1,4);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (1,5);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (2,1);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (3,5);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (4,1);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (5,1);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (6,4);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (7,3);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (8,1);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (9,1);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (10,1);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (11,1);
INSERT INTO INVOICES_TAXES (invoice_id, taxes_id) VALUES (12,1);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (1, 1, 5, 150);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (1, 2, 1, 5.4);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (1, 3, 10, 1560);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (3, 8, 5, 3.2);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (4, 1, 25, 263.5);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (4, 9, 2, 35.4);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (1, 9, 36, 5987.25);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (1, 8, 250, 15000);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (1, 7, 1, 3.6);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (1, 6, 1, 0.98);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (1, 5, 9, 31.2);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (2, 1, 5, 150);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (3, 1, 5, 150);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (4, 7, 5, 150);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (10, 1, 5, 150);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (11, 1, 5, 150);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (9, 1, 5, 150);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (9, 2, 5, 150);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (9, 3, 5, 150);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (5, 1, 5, 150);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (6, 1, 5, 150);
INSERT INTO INVOICE_DETAILS (invoice_id, product_id, cant, price) VALUES (7, 1, 5, 150);
